#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  frontRight,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  frontLeft,      sensorNone)
#pragma config(Motor,  port2,           RDriveBase,    tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           LDriveBase,    tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           topRightLift,  tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           bottomRightLift, tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define LOOP_SPEED              25
#define MAX_POWER              127
#define MIN_POWER             -127
#define PID_SENSOR_INDEX    myEncoder
#define PID_SENSOR_SCALE    1

#define PID_MOTOR_INDEX     myMotor
#define PID_MOTOR_SCALE     -1

#define PID_INTEGRAL_LIMIT  50

float  pid_Kp = 2.0;
float  pid_Ki = 0.04;
float  pid_Kd = 0.0;

static int   pidRunning = 1;
static float pidRequestedValue;

// final motor drive
long            motor_driveR;            ///< final motor control value RIGHT
long            motor_driveL;            /// LEFT

/*///////////////////////////////////////////////////////////
/////                      __ ___  ____                 /////
/////                     / /|__ \|  _ \                /////
/////                    / /_   ) | |_) |               /////
/////                   | '_ \ / /|  _ <                /////
/////                   | (_) / /_| |_) |               /////
/////                    \___/____|____/                /////
///// Team 62K Robot                                    /////
///// Main Code                                         /////
///// Authors: Abner Benitez                            /////
///// Since: Oct. 30, 2016                              /////
*////////////////////////////////////////////////////////////

//setters
void
setMotorL( int valueL )
{
  motor[ LDriveBase ] = valueL;
}

void
setMotorR( int valueR )
{
  motor[ RDriveBase ] = valueR;
}

//task that tests individual motors or groups of motors
task main()
{
	while (true) //try using '1'
  {
    //left drive with deadbands
    setMotorL(abs(vexRT[ Ch3 ]) > 15 ? vexRT[ Ch3 ] : 0);

    //right drive with deadbands
    setMotorR(abs(vexRT[ Ch2 ]) > 15 ? vexRT[ Ch2 ] : 0);

    //drivebase
    if(vexRT[ Btn7R ])
      motor[ RDriveBase ] = 127;
    else motor[ RDriveBase ] = 0;

    if(vexRT[ Btn7L ] == 1)
    	motor[ LDriveBase ] = 127;
   	else motor[ LDriveBase ] = 0;

   	//lift
   	if(vexRT[ Btn8L ] == 1)
    	motor[ leftLift ] = 127;
   	else motor[ leftLift ] = 0;

   	if(vexRT[ Btn8R ] == 1)
    	motor[ topRightLift ] = 127;
   	else motor[ topRightLift ] = 0;

   	if(vexRT[ Btn8D ] == 1)
    	motor[ bottomRightLift ] = 127;
   	else motor[ bottomRightLift ] = 0;


    	wait1Msec(20); //don't hog the CPU :)
  }
}
