#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightClawPot,   sensorPotentiometer)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightClaw,     tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           LDriveBase,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           RDriveBase,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           LFrontDriveBase, tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port5,           RFrontDriveBase, tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           leftClaw,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port8,           rightMidLift,  tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           rightLift,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          leftMidLift,   tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define LOOP_SPEED              25
#define MAX_POWER              127
#define MIN_POWER             -127
#define TPR_STANDARD				 627.2
#define TPR_HIGH_SPEED			 	 392
#define TPR_TURBO					 261.333


#define SAFETY_DELAY					 200
#define CLAW_TRIGGER					1028 //last working val is 800
#define CLAW_LIMIT						 //find the right val for this
#define CLAW_GRASP_POWER			 -0


// final motor drive
long            motor_driveR;            /// RIGHT
long            motor_driveL;            /// LEFT


/*///////////////////////////////////////////////////////////
/////                     __ ___  _  __                 /////
/////                    / /|__ \| |/ /                 /////
/////                   / /_   ) | ' /                  /////
/////                  | '_ \ / /|  <                   /////
/////                  | (_) / /_| . \                  /////
/////                   \___/____|_|\_\                 /////
/////                                                   /////
///// Team 62K Robot                                    /////
///// Main Code                                         /////
///// Authors: Abner Benitez                            /////
///// Last Modified: Dec. 21, 2016                      /////
*////////////////////////////////////////////////////////////

/*
To Do List
1. Add slew rate control
2. Experiment with trim on lift
3. Switch claw power so + -> claw close
4. Experiment with a auto liftUp + clawOpen + liftDown for teleOp
5. Use the preprocessor
6. Auton methods needs some more testing
7. Experiment with true speed :D
8. Max pot value is 4095
*/

#warning "setters"
//universal setters
void
setSensorVal()
{
	//don't set potentiometer values here

}


//setters for TeleOp
void
setLDriveBase( int valueL )
{
	motor[ LDriveBase ] = valueL;
	motor[ LFrontDriveBase ] = valueL;
}


void
setRDriveBase( int valueR )
{
	motor[ RDriveBase ] = valueR;
	motor[ RFrontDriveBase ] = valueR;
}


#warning "action methods"
//setters for Autonomous
void
setLDriveBase( int valueL, int time )
{
	setLDriveBase(valueL/2);
	delay( SAFETY_DELAY );

	setLDriveBase(valueL/2);
	sleep( time );
}


void
setRDriveBase( int valueR, int time )
{
	setRDriveBase(valueR/2);
	delay( SAFETY_DELAY );

	setRDriveBase(valueR/2);
	sleep( time );
}



//action methods for TeleOp
void
move( int left, int right )
{
	setLDriveBase( left );
	setRDriveBase( right );
}


void
setLift( int power )
{
	motor[ leftMidLift ] = power;
	motor[ leftLift ] = power;
	motor[ rightMidLift ] = power;
	motor[ rightLift ] = power;
}


void
setClaw( int power )
{
	motor[ leftClaw ] = power;
	motor[ rightClaw ] = power;

}


//action methods for Autonomous
void
move( int time, int left, int right )
{
	setLDriveBase( left, time );
	setRDriveBase( right, time );

	setLDriveBase( left, 0 );
	setRDriveBase( right, 0 );
}


void
setLift( int time, int power )
{
	setLift(power/2);
	sleep( SAFETY_DELAY );

	setLift(power);
	delay( time );

	setLift(0);
	//sleep(100);
}


void
setClaw( int time, int power )
{
	motor[ leftClaw ] = power;
	motor[ rightClaw ] = power;
	sleep( time );
}


#warning "stopAll"
//stops everything
void
allStop()
{
	move( 1000, 0, 0 );
	setLift( 1000, 0 );
	setClaw( 1000, 0 );
}

#warning "PID Controller"
task PIDclaw()
{
	float Kp

	while(1)
	{

	}
}

task PIDdriveBase()
{

}

#warning "pre-auton"
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	setSensorVal();
	//clearLCDLine(0);
	displayLCDCenteredString(0, "Pre-auton");
}


#warning "autonomous"
task autonomous()
{
	//DB: positive=forwards
	//lift:positive=down
	//claw: positive=open
	setClaw(-127);
	//wait1Msec(2000)
	wait1Msec(1500);
	setClaw(-30);
	setLDriveBase(127);
	setRDriveBase(127);
	wait1Msec(1000);
	setLDriveBase(0);
	setRDriveBase(0);
	wait1Msec(10);
	setRDriveBase(-127);
	setLDriveBase(127);
	wait1Msec(1000);
	setLDriveBase(0);
	setRDriveBase(0);
	wait1Msec(10);
	setLift(-127);
	wait1Msec(1000);
	setLift(0);
	setRDriveBase(-127);
	setLDriveBase(-127);
	wait1Msec(2500);
	setLift(-127);
	setClaw(127);
	wait1Msec(1000);
	setClaw(0);
	wait1Msec(500);
	setLift(0);
	wait1Msec(500);
	setLift(-30);
	wait1Msec(200);
	stopAllMotors();

	// Remove this function call once you have "real" code.
	//AutonomousCodePlaceholderForTesting();
	//clearLCDLine(0);
	//displayLCDCenteredString(0, "Autonomous testing Abner"); //this is temp
}


#warning "usercontrol"
task usercontrol()
{
	setSensorVal();
	//clearLCDLine(0);
	displayLCDCenteredString(0, "Usercontrol testing Abner"); //this is temp

	while (1)
	{
		//drive base
		setLDriveBase(abs(vexRT[ Ch3 ]) > 20 ? vexRT[ Ch3 ] : 0);
		setRDriveBase(abs(vexRT[ Ch2 ]) > 20 ? vexRT[ Ch2 ] : 0);

		//lift
		setLift((vexRT[ Btn6U ] - vexRT[ Btn6D ]) * -127);
		//setLift(vexRT[ Btn6U ] || vexRT[ Btn6D ] ? (vexRT[ Btn6U ] - vexRT[ Btn6D ]) * -127 : 20); //experiment with Trim, careful with stalling

		//claw

		//if((vexRT[ Btn5U ] || vexRT[ Btn5D ]) && (SensorValue[ rightClawPot ] <= CLAW_TRIGGER))
		//	setClaw(CLAW_GRASP_POWER);

		//if((vexRT[ Btn5U ] + vexRT[ Btn5D ] != 1) && (SensorValue[ rightClawPot ] > CLAW_TRIGGER))
		//	setClaw((vexRT[ Btn5U ] - vexRT[ Btn5D ]) * -127);

		if(vexRT[ Btn5U ] || vexRT[ Btn5D ]){
			if(vexRT[Btn5U]&&SensorValue[ rightClawPot ] <= CLAW_TRIGGER)
				setClaw(CLAW_GRASP_POWER);
			else setClaw((vexRT[ Btn5U ] - vexRT[ Btn5D ]) * -127);
		}
		//else if(SensorValue[ rightClawPot ] <= CLAW_TRIGGER){
		//	setClaw(CLAW_GRASP_POWER);
		//	if(vexRT[Btn6D]+vexRT[Btn6U]==0)
		//		setLift(-10);
		//}
		else
			setClaw(0);

		//auto claw grasp
		//if(SensorValue[ rightClawPot ] < CLAW_TRIGGER && (vexRT[ Btn5U ] + vexRT[ Btn5D ] == 0))

		//PID (yay)
		//startTask(PIDclaw());

		wait1Msec(20); //don't hog the CPU :)
	}
}
