#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, I2C_1,  RDrivebaseEncoder, sensorNone)
#pragma config(Sensor, I2C_2,  LDriveBaseEncoder, sensorNone)
#pragma config(Motor,  port1,           rightClaw,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LDriveBase1,   tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           RDriveBase1,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           leftClaw,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           RDriveBase2,   tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           rightMidLift,  tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           leftLift,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LDriveBase2,   tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          leftMidLift,   tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define LOOP_SPEED              25
#define MAX_POWER              127
#define MIN_POWER             -127

#define SAFETY_DELAY				200


// final motor drive
long            motor_driveR;            /// RIGHT
long            motor_driveL;            /// LEFT


/*///////////////////////////////////////////////////////////
/////                      __ ___  ____                 /////
/////                     / /|__ \|  _ \                /////
/////                    / /_   ) | |_) |               /////
/////                   | '_ \ / /|  _ <                /////
/////                   | (_) / /_| |_) |               /////
/////                    \___/____|____/                /////
///// Team 62K Robot                                    /////
///// Main Code                                         /////
///// Authors: Abner Benitez                            /////
///// Since: Nov. 10, 2016                              /////
*////////////////////////////////////////////////////////////

/*
To Do List
1. Try an empty main()
2. what does it mean to have greater resolution in sensors?
3. startTask( ); gotta use this within tasks
4. nMotorEncoder[ ]
5. Stop sudden acceleration
6. Map out TeleOp buttons
7. Fiddle with claw and arm function in TeleOp
*/

//setters


void setLDriveBase(int valueL){
	motor(LDriveBase1)=valueL;
	motor(LDriveBase2)=valueL;
}

void setRDriveBase(int valueR){
	motor(RDriveBase1)=valueR;
	motor(RDriveBase2)=valueR;
}

void
setDriveBase(int power){
	setRDriveBase(power);
	setLDriveBase(power);
}

//action methods


void
setArms( int time, int power )
{
	motor[ leftMidLift ] = power/2;
	motor[ leftLift ] = power/2;
	motor[ rightMidLift ] = power/2;
	motor[ rightLift ] = power/2;
	delay(SAFETY_DELAY);

	motor[ leftMidLift ] = power;
	motor[ leftLift ] = power;
	motor[ rightMidLift ] = power;
	motor[ rightLift ] = power;
	delay(time);

	motor[ leftMidLift ] = 0;
	motor[ leftLift ] = 0;
	motor[ rightMidLift ] = 0;
	motor[ rightLift ] = 0;
	//delay(100);
}

//setArms for TeleOp
void
setArms( int power )
{
	motor[ leftMidLift ] = power;
	motor[ leftLift ] = power;
	motor[ rightMidLift ] = power;
	motor[ rightLift ] = power;
}

void
setClaw( int time, int power)
{
	motor[ leftClaw ] = power/2;
	motor[ rightClaw ] = power/2;
	delay(SAFETY_DELAY);

	motor[ leftClaw ] = power;
	motor[ rightClaw ] = power;
	delay(time);

	motor[ leftClaw ] = 0;
	motor[ rightClaw ] = 0;
	//delay(100)
}

void setClaw(int val){
	motor[ leftClaw ]=val;
	motor[ rightClaw ]=val;
}


//stops everything
void
allStop(){
	setDriveBase(0);
	setArms(0);
	setClaw(0)

}





void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

//tasks
task autonomous(){
	setClaw(MAX_POWER);
	delay(1250);
	setClaw(10);
	setArms(MIN_POWER);
	delay(1000);
	setArms(0);
	setDriveBase(MAX_POWER);
	delay(500);
	setRDriveBase(MAX_POWER);
	setLDriveBase(MIN_POWER);
	delay(750);
	allStop();
	delay(1000);
	setDriveBase(MIN_POWER);
	delay(1250);
	setDriveBase(0);
	setArms(MIN_POWER);
	delay(1500);
	setArms(0);
	setClaw(MIN_POWER);
	delay(200);
	setClaw(0);

}


task usercontrol()
{
	while (true){
		setLDriveBase(vexRT[Ch3]); //mess with deadbands
		setRDriveBase(vexRT[Ch2]);


		/*
		// keep the lift up when holding stars
		if(vexRT[ Btn5U ] || vexRT[ Btn6U ]) //test with == 1
		setArms(10);
		*/
		setArms(((vexRT[ Btn7U ]||vexRT[ Btn7D ]||vexRT[ Btn7R]||vexRT[ Btn7L ]) - (vexRT[ Btn8U ]||vexRT[ Btn8D ]||vexRT[ Btn8R]||vexRT[ Btn8L ])) * -127);

		setClaw(((vexRT[ Btn6D ]||vexRT[ Btn6U]) - (vexRT[ Btn5D ]||vexRT[ Btn5U ]))*-127);
	}
}
