#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  RDrivebaseEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LDriveBaseEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightClaw,     tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           LDriveBase,    tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           RDriveBase,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           leftClaw,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           rightMidLift,  tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          leftMidLift,   tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define LOOP_SPEED              25
#define MAX_POWER              127
#define MIN_POWER             -127
#define PID_SENSOR_INDEX    myEncoder
#define PID_SENSOR_SCALE    1

#define PID_MOTOR_INDEX     myMotor
#define PID_MOTOR_SCALE     -1

#define PID_INTEGRAL_LIMIT  50

#define SAFETY_DELAY				200

float  pid_Kp = 2.0;
float  pid_Ki = 0.04;
float  pid_Kd = 0.0;

static int   pidRunning = 1;
static float pidRequestedValue;

// final motor drive
long            motor_driveR;            /// RIGHT
long            motor_driveL;            /// LEFT


/*///////////////////////////////////////////////////////////
/////                     __ ___  _  __                 /////
/////                    / /|__ \| |/ /                 /////
/////                   / /_   ) | ' /                  /////
/////                  | '_ \ / /|  <                   /////
/////                  | (_) / /_| . \                  /////
/////                   \___/____|_|\_\                 /////
/////                                                   /////
///// Team 62K Robot                                    /////
///// Main Code                                         /////
///// Authors: Abner Benitez                            /////
///// Last Modified: Nov. 23, 2016                      /////
*////////////////////////////////////////////////////////////

/*
To Do List
1. Try an empty main()
2. what does it mean to have greater resolution in sensors?
3. startTask( ); gotta use this within tasks
4. nMotorEncoder[ ]
5. Stop sudden acceleration
6. Map out TeleOp buttons
7. Fiddle with claw and arm function in TeleOp
*/

#warning "setters"
//setters for Autonomous
void
setLDriveBase( int valueL, int time )
{
	motor[ LDriveBase ] = valueL/2;
	delay( SAFETY_DELAY );

	motor[ LDriveBase ] = valueL;
	delay( time );
}


void
setRDriveBase( int valueR, int time )
{
	motor[ RDriveBase ] = valueR/2;
	delay( SAFETY_DELAY );

	motor[ RDriveBase ] = valueR;
	delay( time );
}



//setters for TeleOp
void
setLDriveBase( int valueL )
{
	motor[ LDriveBase ] = valueL;
}


void
setRDriveBase( int valueR )
{
	motor[ RDriveBase ] = valueR;
}


#warning "action methods"
//action methods for Autonomous
void
move( int time, int left, int right )
{
	setLDriveBase( left, time );
	setRDriveBase( right, time );

	setLDriveBase( left, 0 );
	setRDriveBase( right, 0 );
}


void
setLift( int time, int power )
{
	motor[ leftMidLift ] = power/2;
	motor[ leftLift ] = power/2;
	motor[ rightMidLift ] = power/2;
	motor[ rightLift ] = power/2;
	delay( SAFETY_DELAY );

	motor[ leftMidLift ] = power;
	motor[ leftLift ] = power;
	motor[ rightMidLift ] = power;
	motor[ rightLift ] = power;
	delay( time );

	motor[ leftMidLift ] = 0;
	motor[ leftLift ] = 0;
	motor[ rightMidLift ] = 0;
	motor[ rightLift ] = 0;
	//delay(100);
}


void
setClaw( int time, int power )
{
	motor[ leftClaw ] = power;
  motor[ rightClaw ] = power;
	delay( time );
}



//action methods for TeleOp
void
move( int left, int right )
{
	setLDriveBase( left );
	setRDriveBase( right );
}


void
setLift( int power )
{
	motor[ leftMidLift ] = power;
	motor[ leftLift ] = power;
	motor[ rightMidLift ] = power;
	motor[ rightLift ] = power;
}


void
setClaw( int power )
{
	motor[ leftClaw ] = power;
	motor[ rightClaw ] = power;

}


#warning "stopAll"
//stops everything
void
stopAll()
{
	move( 1000, 0, 0 );
	setLift( 1000, 0 );
	setClaw( 1000, 0 );
}


//task
#warning "PID Controller"
task pidController()
{
	/*
	float  pidSensorCurrentValue;

	float  pidError;
	float  pidLastError;
	float  pidIntegral;
	float  pidDerivative;
	float  pidDrive;

	// If we are using an encoder then clear it
	if( SensorType[ PID_SENSOR_INDEX ] == sensorQuadEncoder )
	SensorValue[ PID_SENSOR_INDEX ] = 0;

	// Init the variables - thanks Glenn :)
	pidLastError  = 0;
	pidIntegral   = 0;

	while( true )
	{
	// Is PID control active ?
	if( pidRunning )
	{
	// Read the sensor value and scale
	pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEX ] * PID_SENSOR_SCALE;

	// calculate error
	pidError = pidSensorCurrentValue - pidRequestedValue;

	// integral - if Ki is not 0
	if( pid_Ki != 0 )
	{
	// If we are inside controlable window then integrate the error
	if( abs(pidError) < PID_INTEGRAL_LIMIT )
	pidIntegral = pidIntegral + pidError;
	else
	pidIntegral = 0;
	}
	else
	pidIntegral = 0;

	// calculate the derivative
	pidDerivative = pidError - pidLastError;
	pidLastError  = pidError;

	// calculate drive
	pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

	// limit drive
	if( pidDrive > PID_DRIVE_MAX )
	pidDrive = PID_DRIVE_MAX;
	if( pidDrive < PID_DRIVE_MIN )
	pidDrive = PID_DRIVE_MIN;

	// send to motor
	motor[ PID_MOTOR_INDEX ] = pidDrive * PID_MOTOR_SCALE;
	}
	else
	{
	// clear all
	pidError      = 0;
	pidLastError  = 0;
	pidIntegral   = 0;
	pidDerivative = 0;
	motor[ PID_MOTOR_INDEX ] = 0;
	}

	// Run at 50Hz
	wait1Msec( 25 );
	}
	*/
}


#warning "pre-auton"
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


#warning "autonomous"
task autonomous()
{
	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}


#warning "usercontrol"
task usercontrol()
{
	while (true)
	{
		setLDriveBase(abs(vexRT[ Ch3 ]) > 15 ? vexRT[ Ch3 ] : 0); //mess with deadbands
		setRDriveBase(abs(vexRT[ Ch2 ]) > 15 ? vexRT[ Ch2 ] : 0);

		/*
		// keep the lift up when holding stars
		if(vexRT[ Btn5U ] || vexRT[ Btn6U ]) //test with == 1
		 setArms(10);
		*/



		wait1Msec(20); //don't hog the CPU :)
	}
}
