#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    rightClawPot,   sensorPotentiometer)
#pragma config(Motor,  port1,           rightClaw,     tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           LDriveBase,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           RDriveBase,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           LFrontDriveBase, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           RFrontDriveBase, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           leftClaw,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           rightMidLift,  tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           rightLift,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          leftMidLift,   tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		motor[ rightClaw ] = vexRT[ Btn7U ] * 100;
		motor[ LDriveBase ] = vexRT[ Btn7R ] * 100;
		motor[ RDriveBase ] = vexRT[ Btn7D ] * 100;

		motor[ leftLift ] = vexRT[ Btn7L ] * 100;


		motor[ leftClaw ] = vexRT[ Btn8U ] * 100;
		motor[ rightMidLift ] = vexRT[ Btn8R ] * 100;
		motor[ rightLift ] = vexRT[ Btn8D ] * 100;
		motor[ leftMidLift ] = vexRT[ Btn8L ] * 100;


		motor[ LFrontDriveBase ] = vexRT[ Btn5U ];
		motor[ RFrontDriveBase ] = vexRT[ Btn5D ];

		//extra buttons
		/*
		motor[  ] = vexRT[ Btn6U ];
		motor[  ] = vexRT[ Btn6D ];
		*/
	}
}
