#pragma config(Motor,  port1,           primary,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[ primary ] = 127;
	delay(30000);
	motor[ primary ]=0;
}
