#pragma config(Motor,  port1,           motorI,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motorII,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor [ motorII ] = 127;
	delay(3000);
	motor[motorII]=0;
}
